# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {}

modules = []

doc_url = "https://stevenborg.github.io/dicom_client/"

git_url = "https://github.com/stevenborg/dicom_client/tree/master/"

def custom_doc_links(name): return None
